cabal-version: 3.0
name: hasql-features
version: 0.1.0.0
library
  build-depends:
    aeson,
    base,
    bytestring,
    hasql,
    scientific,
    text,
    time,
    uuid,
    vector,
  exposed-modules:
    Queries
    Queries.DeleteUsers
    Queries.FindMembers
    Queries.FindPosts
    Queries.FindUserByName
    Queries.FindUsers
    Queries.GetEvent
    Queries.Internal
    Queries.Types
