{- This file was auto-generated by sqlc-hs. -}
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeFamilies #-}
module Pulse.Database.Types where

import qualified Control.Monad
import qualified Data.Text
import qualified Database.PostgreSQL.Simple.FromField
import qualified Database.PostgreSQL.Simple.FromRow
import qualified Database.PostgreSQL.Simple.ToField
import qualified Database.PostgreSQL.Simple.ToRow
import Pulse.Database.Internal
import Prelude hiding (Enum)
import qualified Prelude

data instance Enum "organization_role"
  = Enum_organization_role_owner
  | Enum_organization_role_admin
  | Enum_organization_role_member
  deriving stock (Eq, Ord, Show, Bounded, Prelude.Enum)

instance Database.PostgreSQL.Simple.ToField.ToField (Enum "organization_role") where
  toField Enum_organization_role_owner = Database.PostgreSQL.Simple.ToField.toField @Data.Text.Text "owner"
  toField Enum_organization_role_admin = Database.PostgreSQL.Simple.ToField.toField @Data.Text.Text "admin"
  toField Enum_organization_role_member = Database.PostgreSQL.Simple.ToField.toField @Data.Text.Text "member"

instance Database.PostgreSQL.Simple.FromField.FromField (Enum "organization_role") where
  fromField field value = do
    typename <- Database.PostgreSQL.Simple.FromField.typename field
    Control.Monad.when (typename /= "organization_role") $
      Database.PostgreSQL.Simple.FromField.returnError Database.PostgreSQL.Simple.FromField.Incompatible field ""
    case value of
      Just "owner" -> pure Enum_organization_role_owner
      Just "admin" -> pure Enum_organization_role_admin
      Just "member" -> pure Enum_organization_role_member
      Just value -> Database.PostgreSQL.Simple.FromField.returnError Database.PostgreSQL.Simple.FromField.ConversionFailed field (show value)
      Nothing -> Database.PostgreSQL.Simple.FromField.returnError Database.PostgreSQL.Simple.FromField.UnexpectedNull field ""

