name: Haskell CI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: false

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # windows-latest]
        ghc: [9.10.1]
    needs: create_release
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up GHC
        uses: haskell-actions/setup@v2.7.11
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Determine target triple
        id: triple
        shell: bash
        run: |
          TRIPLE=$(ghc --print-target-platform)
          # add .exe on Windows
          if [ "${RUNNER_OS}" = "Windows" ]; then
            TRIPLE="${TRIPLE}.exe"
          fi
          echo "triple=$TRIPLE" >> $GITHUB_OUTPUT

      - name: Configure & build
        run: |
          cabal configure -O1 --enable-split-sections
          cabal build exe:sqlc-hs
          cabal test

          mkdir artifacts
          cp $(cabal list-bin exe:sqlc-hs) "./artifacts/sqlc-hs_${{ github.ref_name }}-${{ steps.triple.outputs.triple }}"
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          files: artifacts/sqlc-hs_${{ github.ref_name }}-${{ steps.triple.outputs.triple }}

  hackage_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up GHC
        uses: haskell-actions/setup@v2.7.11
        with:
          ghc-version: 9.10.1

      - name: Upload to Hackage
        env:
          HACKAGE_TOKEN: ${{ secrets.HACKAGE_TOKEN }}
        run: |
          cabal sdist
          TARBALL=$(ls dist-newstyle/sdist/*.tar.gz)
          cabal upload --publish --token="$HACKAGE_TOKEN" "$TARBALL"

  # build-wasm:
  #   runs-on: ubuntu-22.04
  #   defaults:
  #     run:
  #       shell: bash

  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Build
  #     run: |
  #       curl https://gitlab.haskell.org/haskell-wasm/ghc-wasm-meta/-/raw/master/bootstrap.sh | sh
  #       source ~/.ghc-wasm/env

  #       rm cabal.project.freeze
  #       wasm32-wasi-cabal update hackage.haskell.org,2025-03-30T20:28:13Z
  #       wasm32-wasi-cabal build --allow-newer exe:sqlc-hs
  #       cp $(wasm32-wasi-cabal list-bin --allow-newer exe:sqlc-hs) "./sqlc-hs-${{ github.ref_name }}.wasm"

  #   - name: Release notes
  #     run: |
  #       SHA256=$(sha256sum "./sqlc-hs-${{ github.ref_name }}.wasm" | awk '{ print $1 }')
  #       cat <<EOF > ${{ github.workspace }}-CHANGELOG.txt
  #       # Configuration

  #       \`\`\`yaml
  #         version: '2'
  #         plugins:
  #           - name: haskell
  #             wasm:
  #               url: https://github.com/alexbiehl/sqlc-hs/releases/download/${{ github.ref_name }}/sqlc-hs-${{ github.ref_name }}.wasm
  #               sha256: $SHA256
  #       \`\`\`
  #       EOF